### ISSUE TITLE
Does it support LLD?

### ISSUE THREAD

**Issue by littlecong** [kmomberg/pyZabbixSender#2]
I don't found any code about "LLD"

**Comment by kmomberg** [comment]
Hi. You're right, there's nothing about LLD (low level discovery) in this library.
The main goal is to be a simple replacement of zabbix_sender implemented in pure Python. Maybe one of the available libraries in https://www.zabbix.org/wiki/Docs/api/libraries#Python will fit your needs.

Regards.
